security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "ALWAYS"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

client:
  endpoint:
    service-1-health-check: http://localhost:8081
